version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: vichynaa/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/media/

  frontend:
    env_file: .env
    image: vichynaa/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  nginx:
    image: vichynaa/foodgram_gateway
    env_file: .env
    ports:
      - 8090:80
    volumes:
      - static:/static/
      - media:/media/