# Generated by Django 4.2.3 on 2023-08-02 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1, message='Введите имя')], verbose_name='имя ингредиента'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(1, message='Введите количество')], verbose_name='мера'),
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.CharField(default=0, max_length=16, validators=[django.core.validators.MinLengthValidator(1, message='Введите количество')], verbose_name='мера'),
        ),
    ]
